plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'idea'
}

version = "${project.mod_version}-mc${project.minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	flatDir { dirs "libs" }
	maven { url "https://maven.fabricmc.net/" }
	maven { url "https://SILENCE-SIMSOOL.github.io/maven-repo/" }
	maven { url = uri("https://api.modrinth.com/maven") }
	maven { url = uri("https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1") }
	maven { url = uri("https://repo.hypixel.net/repository/Hypixel/") }
}

idea {
	module {
		downloadSources = false
		downloadJavadoc = false
	}
}

loom {
	mods {
		"profileviewer" {
			sourceSet sourceSets.main
		}
	}

	runConfigs.named("client") {
		ideConfigGenerated = true
		property "devauth.enabled", "true"
		property "devauth.account", "main"
	}

	runConfigs.named("server") {
		ideConfigGenerated = false
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	runtimeOnly("me.djtheredstoner:DevAuth-fabric:${property("devauth_version")}")

	def lwjglVersion = project.property("minecraft_lwjgl_version")
	implementation "org.lwjgl:lwjgl-nanovg:${lwjglVersion}"
	["windows", "linux", "macos", "macos-arm64"].each { os ->
		implementation "org.lwjgl:lwjgl-nanovg:${lwjglVersion}:natives-${os}"
	}

	def lucentVersion = "${project.lucent_version}-${project.minecraft_version}-${project.lucent_library}"
	implementation "com.github.SILENCE-SIMSOOL:lucent:${lucentVersion}"

	implementation files("libs/LucentClient-1.0.21-mc26.2-lite.jar")
	implementation files("libs/velocity-native-3.4.0.jar")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = "UTF-8"
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName
	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
}
