# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.0
maven_group=silence.simsool.profileviewer
archives_base_name=ProfileViewer

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Dependencies
fabric_version=0.162.0+26.3
devauth_version=1.2.2
skija_version=0.143.17
types_version=0.2.0
lucent_version=1.5.7
lucent_library=1
